[package]
name = "edjr"
version = "0.1.4"
rust-version.workspace = true
edition.workspace = true
description = "Elite Dangerous Journal Reader"
authors = ["stefanlight8 <64615032+stefanlight8@users.noreply.github.com>"]
readme = "README.md"
license.workspace = true
repository = "https://github.com/stefanlight8/edjr"
keywords = ["elite-dangerous", "journal"]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true

[workspace]
resolver = "3"
members = ["examples/*"]

[workspace.package]
rust-version = "1.85.1"
edition = "2024"
license = "MIT"

[workspace.dependencies]
edjr = { path = "." }

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

tokio = { version = "1.52.3", features = ["fs", "io-util"], optional = true }
async-stream = { version = "0.3.6", optional = true }
futures-lite = { version = "2.6.1", optional = true }
serde_repr = "0.1.20"

[features]
tokio = ["dep:tokio"]
stream = ["dep:async-stream", "dep:futures-lite"]

full = [
    "ammo",
    "approach",
    "backpack",
    "body",
    "bounty",
    "broker",
    "cargo",
    "codex",
    "colonisation",
    "commander",
    "community_goal",
    "consumable",
    "crew",
    "crime",
    "data",
    "died",
    "disembark",
    "dock",
    "drones",
    "embark",
    "engineer",
    "faction",
    "fc",
    "fighter",
    "fileheader",
    "fines",
    "friends",
    "fsd",
    "fss",
    "fuel",
    "game",
    "hull",
    "impound",
    "interdiction",
    "jetcone",
    "jump",
    "liftoff",
    "loadout",
    "location",
    "market",
    "material",
    "mission",
    "module",
    "music",
    "navigation",
    "outfitting",
    "passengers",
    "powerplay",
    "pvp",
    "ranks",
    "repair",
    "reputation",
    "resurrect",
    "saa",
    "scan",
    "screenshot",
    "search_and_rescue",
    "shield",
    "ship",
    "shipyard",
    "squadron",
    "srv",
    "statistics",
    "supercruise",
    "synthesis",
    "target",
    "taxi",
    "text",
    "touchdown",
    "under_attack",
    "uss",
    "vehicle",
    "voucher",
    "weapon",
    "wing",
]
ammo = []
approach = []
backpack = []
body = []
bounty = []
broker = []
cargo = []
codex = []
colonisation = []
commander = []
community_goal = []
consumable = []
crew = []
crime = []
data = []
died = []
disembark = []
dock = []
drones = []
embark = []
engineer = []
faction = []
fc = []
fighter = []
fileheader = []
fines = []
friends = []
fsd = []
fss = []
fuel = []
game = []
hull = []
impound = []
interdiction = []
jetcone = []
jump = []
liftoff = []
loadout = []
location = []
market = []
material = []
mission = []
module = []
music = []
navigation = []
outfitting = []
passengers = []
powerplay = []
pvp = []
ranks = []
repair = []
reputation = []
resurrect = []
saa = []
scan = []
screenshot = []
search_and_rescue = []
shield = []
ship = []
shipyard = []
squadron = []
srv = []
statistics = []
supercruise = []
synthesis = []
target = []
taxi = []
text = []
touchdown = []
under_attack = []
uss = []
vehicle = []
voucher = []
weapon = []
wing = []
