[package]
name = "statistics"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono = "0.4.44"
clap = "4.6.1"
edjr = {workspace = true, features = ["tokio", "stream", "dock", "location", "loadout", "fileheader", "bounty", "faction", "commander", "powerplay"]}
futures-lite = "2.6.1"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "fs"] }
